name: build_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2

  share_plus: ^10.1.4

  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.4
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#2F80ED"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  min_sdk_android: 23

flutter_native_splash:
  color: "#F4F7FB"
  image: assets/icons/app_icon.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#F4F7FB"
    image: assets/icons/app_icon.png